# فصل دوم: شبیه‌سازی از توزیع‌های آماری

در بیشتر دروس نظری و عملی رشته آمار فرض می‌شود متغیرهای تصادفی $X_{1},\ldots,X_{n}$ نمونه‌ای تصادفی از جامعه‌ای با تابع چگالی (جرم) احتمال $f_{\theta}(x)$ هستند. معمولاً بر اساس مقادیر مشاهده شده این نمونه تصادفی (مشاهدات $x_{1},\ldots,x_{n}$) در مورد پارامترهای مجهول $f_{\theta}(x)$ استنباط می‌شود. در این فصل مایلیم با فرض معلوم بودن فرم ریاضی تابع چگالی (جرم) احتمال و معلوم بودن پارامترهای آن به تولید متغیرهای $X_{1},\ldots,X_{n}$ بپردازیم.

تولید عدد تصادفی از یک توزیع احتمال، شبیه‌سازی توزیع احتمال نامیده می‌شود. نرم‌افزار `R` با توجه به قابلیت‌های فراوان، ابزار اصلی برای پیاده‌سازی الگوریتم‌های شبیه‌سازی می‌باشد.

## شبیه‌سازی از توزیع‌های گسسته

شبیه‌سازی از توزیع‌های گسسته به سه روش انجام می‌گیرد:

1.  روش وارون

2.  روش رد-پذیرش

3.  روش مرکب

### روش وارون

متداول‌ترین روش برای شبیه‌سازی از متغیرهای تصادفی روش وارون است. اساس کار این روش استفاده از قضیه تبدیل انتگرالی احتمال[^ch_2-1] (برای تولید متغیرهای تصادفی پیوسته) و عکس آن[^ch_2-2] (برای تولید متغیرهای تصادفی گسسته) می‌باشد.

[^ch_2-1]: Probability Integral Transform

[^ch_2-2]:  Inverse Probability Integral Transform

[**قضیه (عکس تبدیل انتگرالی احتمال):**]{style="color: blue;"} فرض کنید $F_{X}(.)$ یک تابع توزیع تجمعی دلخواه (گسسته یا پیوسته) و $U$ یک متغیر تصادفی با توزیع یکنواخت پیوسته روی بازه `(0,1)` باشد. اگر $F_X^{-1}(.)$ وارون تعمیم یافته این تابع توزیع باشد که به صورت زیر تعریف می‌شود:

\begin{align*}
        F^{-1}(u)=\inf\{x|F_{X}(x)\geq u\} = \sup\{x|F_{X}(x)\leq u\}
\end{align*}

در این صورت متغیر تصادفی $F_X^{-1}(U)$ دارای تابع توزیع $F_{X}(.)$ است، یعنی دو متغیر $F_X^{-1}(U)$ و $X$ هم توزیع هستند.

------------------------------------------------------------------------

[**نکته:**]{style="color: green;"}برای سادگی در نوشتار و همچنین مشابه‌ بودن نمادگذاری دو متغیر تصادفی هم توزیع، در ادامه این فصل متغیر تصادفی $F_X^{-1}(U)$ را با نماد $X^{*}$ نشان می‌دهیم. یعنی بر اساس قضیه قبل داریم

$$
X^{*} \overset{D}{=} X \quad \Rightarrow \quad F_X^{-1}(U) \sim F_X
$$

با استفاده از قضیه فوق و با در اختیار داشتن تابع توزیع $F_{X}(x)$ می‌توان مقادیری از متغیر تصادفی $X^{*}$ را شبیه‌سازی کرد و چون این متغیر با متغیر هدف $X$، هم‌توزیع می‌باشد، می‌توان این مقادیر تولید شده را به عنوان مقادیر تولید شده از متغیر هدف در نظر گرفت.

مثال‌های زیر شیوه استفاده از قضیه فوق را نشان‌ می‌دهند.
