# فصل اول: تولید اعداد تصادفی

## مقدمه

شبیه سازی یک ابزار قدرتمند برای طراحی و تحلیل سیستم‌ها یا فرآیندهای پیچیده است که با ارائه حالت یا نمونه‌های مشابه با نمونه اصلی، به استفاده کنندگان از آن، امکان انجام آزمایش با سیستم‌هایی را می‌دهد که در عمل غیر ممکن یا پر هزینه هستند.

**مثال:**

-   آموزش خلبانی

-   مانور زلزله

-   سینما چندبُعدی

## شبیه‌سازی در آمار

از کاربردهای شبیه‌سازی در آمار می‌توان موارد زیر را نام برد:

-   تولید اعداد تصادفی و شبه‌تصادفی

-   تولید داده‌های تصادفی از توزیع‌های گسسته یا پیوسته

-   محاسبه (تقریب) انتگرال‌ها و احتمال‌های پیچیده

-   تقریب امید ریاضی توابعی از متغیرهای تصادفی

-   تقریب توان یک آزمون

### اعداد تصادفی و شبه‌تصادفی

**اعداد تصادفی (Random Numbers):** اعدادی هستند که بر مبنای یک سری جریانات یا بر اساس یک منبع خارجی بدون هیچ رابطه خاصی تولید می‌شوند، بنابراین این اعداد قابلیت باز تولید را ندارند، یعنی اگر مجموعه‌ای از اعداد از اعداد تصادفی تولید شوند دوباره [نمی‌توان]{style="color: red"} دقیقاً همان اعداد را تولید کرد.

**اعداد شبه‌تصادفی (PseudoRandom Numbers):** اعدادی هستند که بر مبنای یک رابطه ریاضی به دست می‌آیند. بنابراین قابلیت بازتولید دارند، یعنی اگر مجموعه‌ای از اعداد از اعداد تصادفی تولید شوند دوباره [می‌توان]{style="color: red"} دقیقاً همان اعداد را تولید کرد.
